<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
class numbersFilipAndrle{
    static public function roundFilipAndrle($zaokrouhli) {
        return round($zaokrouhli);
        
    }
   static public function ceilFilipAndrle($zaokrouhlinahoru) {
       return ceil($zaokrouhlinahoru);
   }
   static public function floorFilipAndrle($zaokrouhlidolu) {
       return floor($zaokrouhlidolu);
   }
   static public function sqrtFilipAndrle($druhaodmocnina) {
       return sqrt($druhaodmocnina);
   }
   static public function powFilipAndrle($mocnina,$mocnitel) {
       return pow($mocnina, $mocnitel);
   }
   static public function sinFilipAndrle($uhel) {
       return sin($uhel);
   }
   static public function cosFilipAndrle($uhel) {
       return cos($uhel);
}
static public function tanFilipAndrle($uhel) {
       return tan($uhel);
}
static public function asinSFilipAndrle($zcislanauhel) {
       return asin($zcislanauhel);
   }
   static public function acosFilipAndrle($zcislanauhel) {
       return acos($zcislanauhel);
}
static public function atanFilipAndrle($zcislanauhel) {
       return atan($zcislanauhel);
}
static public function fmodFilipAndrle($zaklad,$delitel) {
    return fmod($zaklad, $delitel);
}
static public function maxFilipAndrle($pole) {
    return max($pole);
}
static public function minFilipAndrle($pole) {
    return min($pole);
}
static public function absFilipAndrle($abscislo) {
    return abs($abscislo);
}
static public function odecitaniFilipAndrle($a,$b) {
    return $a-$b;
}
static public function scitaniFilipAndrle($a,$b) {
    return $a+$b;
}
static public function deleniFilipAndrle($a,$b) {
    return $a/$b;
}
static public function nasobeniFilipAndrle($a,$b) {
    return $a*$b;
}
